### ISSUE TITLE
(closed) 

### ISSUE THREAD

**Issue by BirkoRuzicka** [nicoFhahn/making_maps_with_r#1]
closed

**Comment by nicoFhahn** [comment]
Hi,

will look into it on Thursday. In the meantime I can only advise you to check google the error message to see whether someone has the same problem.

Best,
Nico

**Comment by BirkoRuzicka** [comment]
thank you. for reference, [this shapefile](https://www.naturalearthdata.com/downloads/110m-physical-vectors/110m-coastline/) loads without a hitch, using the same command.

**Comment by nicoFhahn** [comment]
I don't have any problem loading the shapefile. Is the shapefile in the same folder as the `.dbf`, `.prj` and `.shx` file?

**Comment by BirkoRuzicka** [comment]
Hi Nico, thank you for looking into this.

Yes, they're all in the same folder. Just to be sure I just re-downloaded the .dbf, .prj, .shp and .shx files, but the error persists. Since you can load the shapefile just fine, it's likely a problem with my setup.

This is the code I'm running in its entirety:

```
> library(raster)
> library(readr)
> library(readxl)
> library(sf)
> library(maps)
> library(spData)

> setwd("~/GitHub/mappingproject")
> bavaria <- read_sf("bavaria.shp")
Error: Cannot open "C:\Users\Birko\Documents\GitHub\mappingproject\bavaria.shp"; The source could be corrupt or not supported. See `st_drivers()` for a list of supported formats.
```

**Comment by nicoFhahn** [comment]
Hi,
it works with your setup as well.
In commit cbc0a96f572f1acfa33e7bb2ec56b1d18d9d8bbc I have added the file as a geojson in the chapter_2 subfolder. Can you check whether you are able to load it using the following command?

    bavaria <- read_sf("datasets/chapter_2/bavaria.geojson")

**Comment by BirkoRuzicka** [comment]
I checked, same error. 

It's probably just something totally ridiculous in the innards of my setup. Please don't spend any more time on this, it's fine!
